version: "3.8"

services:
  app1:
    build: backend/app
    container_name: app1
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8005:8000
    volumes:
      - ./backend/app:/app

  app2:
    build: backend/app
    container_name: app2
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8006:8000
    volumes:
      - ./backend/app:/app

  app3:
    build: backend/app
    container_name: app3
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - 8007:8000
    volumes:
      - ./backend/app:/app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 8000:80
    volumes:
      - ./backend/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
